details:
  - name: BmDetailPageHandler
    method: NewDetailPageHandler
    args:
      useragent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
      shopnameparam: "//div[@class='shop-name']/h1"  
      typeparam: "//div[@class='breadcrumb']/b[2]"
      regionparam: "//div[@class='breadcrumb']/b[3]"
      priceparam: "//div[@class='rst-taste']/span"
      contentcountparam: "//div[@class='rst-taste']/a/span"
      createtimeparam: "//div[@class='cont']"
      introductionparam: "//div[@class='con J_showWarp']"
      phoneparam: "//div[@class='shopinfor']/p/span"
      addressparam: "//div[@class='shop-addr']/span"
      branchcount: "//div[@class='shop-name']/a" 
lists:
  - name: BmListPageHandler
    method: NewListPageHandler
    args:
      detail: BmDetailPageHandler
      plb: 1
      pub: 50
      useragent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36"
      handlerpattern: "dianping.com"
      linkqueryparam: "//ul[@class='shop-list']/li/a"
      
entry:
  - name: BmEntry
    title: actvs
    method: NewBmEntryHandler
    url: http://www.dianping.com/beijing/ch70/g33803
    handler: BmListPageHandler
  - name: BmEntry
    title: daycare
    method: NewBmEntryHandler
    url: http://www.dianping.com/beijing/ch70/g33803
    handler: BmListPageHandler
